import cv2
import tkinter as tk
from PIL import Image, ImageTk
from tkinter import *
img = cv2.imread("C:\\Users\\candi\\PycharmProjects\\pythonProject2\\pirinc2.jpeg")
img = cv2.resize(img, (700, 500))
cevir = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
ret, threshold = cv2.threshold(cevir, 55, 250, cv2.THRESH_BINARY)
pirincsay, _ = cv2.findContours(threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
pirincss = len(pirincsay)
def goruntu(thresh_degeri):
    sonsayim, arkaplan = pirincpg(thresh_degeri)
    arkaplan = cv2.cvtColor(arkaplan, cv2.COLOR_BGR2RGB)
    arkaplan = Image.fromarray(arkaplan)
    arkaplan = ImageTk.PhotoImage(arkaplan)
    canvas.config(width=arkaplan.width(), height=arkaplan.height())
    canvas.create_image(0, 0, anchor=tk.NW, image=arkaplan)
    canvas.image = arkaplan


def pirincpg(thresh_degeri):
    img = cv2.imread("C:\\Users\\candi\\PycharmProjects\\pythonProject2\\pirinc2.jpeg")
    img = cv2.resize(img, (700, 500))
    cevir = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    ret, threshold = cv2.threshold(cevir, thresh_degeri, 250, cv2.THRESH_BINARY)
    pirincsay, _ = cv2.findContours(threshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    sonsayim = len(pirincsay)
    arkaplan = cv2.bitwise_and(img, img, mask=threshold)
    cv2.imshow("Son hali", arkaplan)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    return sonsayim, arkaplan
arayuz = tk.Tk()
arayuz.resizable(width=False, height=False)
img = tk.PhotoImage(file="C:\\Users\\candi\\PycharmProjects\\pythonProject2\\princ2d.png")
width, height = img.width(), img.height()
canvas = tk.Canvas(arayuz, width=width, height=height)
canvas.pack()
canvas.create_image((0, 0), image=img, anchor="nw")
ekran_yuk = arayuz.winfo_screenwidth()
ekran_uzun = arayuz.winfo_screenheight()
arayuz.geometry(f"1000x700+{(ekran_yuk//2)-500}+{(ekran_uzun//2)-350}")
arayuz.resizable(width=False, height=False)
arayuz.title("Pirinc Hesaplama Programı")
bosluk = tk.Label(arayuz,text=" ", bg="Orange")
bosluk.pack()
bilgi = tk.Label(arayuz, text="02210201019 Barkın Çandır", fg="Black", bg="Gray",bd=4 , relief=RAISED, anchor="w")
bilgi.place(x=2,y=2)
hosg = tk.Label(arayuz, text="Hoşgeldiniz <3", fg="Black", bg="Gray", bd=3, relief=RAISED)
hosg.place(x=450, y=25)
threshold_label = tk.Label(arayuz, text="Threshold Değeri Giriniz===> ", fg="Black", bg="Gray", bd=3, relief=RAISED)
threshold_label.place(x=325, y=75)
threshold_entry = tk.Entry(arayuz, fg="Black", bg="White", bd=3, relief=RAISED)
threshold_entry.place(x=500, y=75)
ark_degeri = tk.PhotoImage()
gor = tk.Button(arayuz, text="Görüntüyü göster", fg="Black", bg="Gray", bd=3, relief=RAISED, command=lambda: goruntu(int(threshold_entry.get())))
gor.place(x=650, y=73)
bilgilendirme = tk.Label(arayuz, text="55 değeri güncel görüntü için iyi bir değer.", fg="White", bg="Black")
bilgilendirme.place(x=375, y=100)
sonsay = tk.Label(arayuz, text=f"Pirinç sayısı: {pirincss}  ", fg="Black", bg="Gray", bd=3, relief=RAISED)
sonsay.place(x=450, y=125)
arayuz.mainloop()